src/TMS.Web/Controllers/AreasController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TMS.Layer.Initialisers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using TMS.Layer.Persistence;
using TMS.ApplicationLayer.Areas.Data;
using TMS.ViewModelLayer.Models.Areas.Pages;
using TMS.Layer.Creators;
using Microsoft.Extensions.Logging;
using TMS.Web.Logging;
using TMS.ModelLayer.Areas;
using TMS.ModelLayer.People;
using TMS.Data.Entities.People;

namespace TMS.Web.Controllers
{
    [Authorize]
    public class AreasController : ControllerBase
    {
        private readonly IInitialiser<AreaPageModelInitialiserData, AreaPageModel> _areasPageInitialiser;
        private readonly UserManager<PersonEntity> _userManager;

        private readonly IWriter<Area, AreaKey> _areaWriter;

        private readonly IInitialiser<DeleteAreaPageModelInitialiserData, DeleteAreaPageModel> _deletePageInitialiser;
        private readonly IInitialiser<AreaDetailsPageModelInitialiserData, AreaDetailsPageModel> _detailsPageInitialiser;
        private readonly IInitialiser<AreaEditPageModelInitialiserData, AreaEditPageModel> _editPageInitialiser;
        private readonly ICreator<Tuple<AreaPageModelBase, PersonKey>> _areaCreator;
        private readonly ILogger<AreasController> _logger;

        public AreasController(
            UserManager<PersonEntity> userManager,
            IInitialiser<AreaPageModelInitialiserData, AreaPageModel> areasPageInitialiser,
            IWriter<Area, AreaKey> areaWriter,
            IInitialiser<DeleteAreaPageModelInitialiserData, DeleteAreaPageModel> deletePageInitialiser,
            IInitialiser<AreaDetailsPageModelInitialiserData, AreaDetailsPageModel> detailsPageInitialiser,
            IInitialiser<AreaEditPageModelInitialiserData, AreaEditPageModel> editPageInitialiser,
            ICreator<Tuple<AreaPageModelBase, PersonKey>> areaCreator,
            ILogger<AreasController> logger) : base(userManager)
        {
            _userManager = userManager;
            _areasPageInitialiser = areasPageInitialiser;
            _areaWriter = areaWriter;
            _deletePageInitialiser = deletePageInitialiser;
            _detailsPageInitialiser = detailsPageInitialiser;
            _editPageInitialiser = editPageInitialiser;
            _areaCreator = areaCreator;
            _logger = logger;
        }

        // GET: Areas
        public async Task<ActionResult> Index()
        {
            var personKey = await GetPersonKey();

            var model = _areasPageInitialiser.Initialise(new AreaPageModelInitialiserData
            {
                CurrentUserKey = personKey
            });

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var model = _editPageInitialiser.Initialise(new AreaEditPageModelInitialiserData
            {
                AreaId = id
            });

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AreaEditPageModel model)
        {
            try
            {
                var personKey = await GetPersonKey();

                _logger.LogInformation(LoggingEvents.UPDATE_ITEM, $"Saving area {model.AreaId}: {model.Name}");

                _areaCreator.Create(new Tuple<AreaPageModelBase, PersonKey>(model, personKey));

                _logger.LogInformation(LoggingEvents.UPDATE_ITEM, $"Saved area {model.AreaId}: {model.Name}");

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.UPDATE_ITEM, ex, $"Failed to save changes to area {model.AreaId}.");
                return View();
            }
        }

        // GET: Areas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Areas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateAreaPageModel model)
        {
            try
            {
                var personKey = await GetPersonKey();

                model.Created = DateTime.UtcNow;

                _areaCreator.Create(new Tuple<AreaPageModelBase, PersonKey>(model, personKey));

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.INSERT_ITEM, ex, "Failed to create area.");
                return View();
            }
        }

        // GET: Areas/Edit/5
        public ActionResult Details(int id)
        {
            var pageModel = _detailsPageInitialiser.Initialise(new AreaDetailsPageModelInitialiserData
            {
                AreaId = id
            });

            return View(pageModel);
        }

        // GET: Areas/Delete/5
        public async Task<ActionResult> Delete(long id)
        {
            var personKey = await GetPersonKey();

            var model = _deletePageInitialiser.Initialise(new DeleteAreaPageModelInitialiserData
            {
                AreaId = id,
                PersonId = personKey.Identifier
            });

            return View(model);
        }

        // POST: Areas/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(DeleteAreaPageModel model)
        {
            try
            {
                _logger.LogInformation(LoggingEvents.DELETE_ITEM, $"Deleting area {model.Id}");

                _areaWriter.Delete(new AreaKey(model.Id));

                _logger.LogInformation(LoggingEvents.DELETE_ITEM, $"Deleted area {model.Id}");

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.DELETE_ITEM, ex, $"Failed to delete area {model.Id}.");
                return View();
            }
        }
    }
}

src/TMS.Web/Views/Shared/FormGroupInput.cshtml
@using TMS.ViewModelLayer.Models.Forms
@model FormGroupInput

<div class="form-group">
    <label asp-for="Value" class="col-md-2 control-label"></label>
    <div class="col-md-10">
        <input asp-for="Value" class="form-control" />
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>
</div>

src/TMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMS.Web</title>

    @*<environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>*@
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/built/bundle.css"/>
    </environment>
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">TMS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="Areas" asp-action="Index">Areas</a></li>
                    <li><a asp-controller="Tags" asp-action="Index">Tags</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - TMS</p>
        </footer>
    </div>

    <environment names="Development,Staging,Production">
        <script type="text/javascript" src="~/built/main.bundle.js"></script>
    </environment>
</body>
</html>